[package]
name = "tfidf-summarizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "summarizer"
crate_type = [ "staticlib" ]

[dependencies]
regex = "1.9.5"